import clsx from 'clsx';
import type { Metadata } from 'next';
import { Red_Hat_Display, Red_Hat_Mono } from 'next/font/google';
import './globals.css';

const redHat = Red_Hat_Display({
  subsets: ['latin'],
  variable: '--font-red-hat',
  weight: ['400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
});

const redHatMono = Red_Hat_Mono({
  subsets: ['latin'],
  variable: '--font-red-hat-mono',
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
});
export const metadata: Metadata = {
  title: 'Muhsin Suny M Portofolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={clsx(redHat.variable, redHatMono.variable, 'antialiased')}
      >
        {children}
      </body>
    </html>
  );
}
